version: '3'

services:
  eventeum:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8060:8060"
    depends_on:

      - postgres
      - kafka
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASS: password
      ETHEREUM_NODE_URL: https://mainnet.infura.io/v3/cb9c97eb8fe34a8c9416aaf979211fad
      ZOOKEEPER_ADDRESS: zookeeper:2181
      KAFKA_ADDRESSES: kafka:19092


  platform:
    build:
      context: .
      dockerfile: Dockerfile-Platform
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - clickhouse
      - kafka
      - eventeum
    environment:
      #CLICKHOUSE_JDBC: jdbc:clickhouse://host.docker.internal:8123?compress=0
      #POSTGRES_JDBC: jdbc:postgresql://host.docker.internal/analysis_platform
      CLICKHOUSE_JDBC: jdbc:clickhouse://clickhouse:8123?compress=0
      CLICKHOUSE_USER: clickhouse_user
      CLICKHOUSE_PASSWORD: password
      POSTGRES_JDBC: jdbc:postgresql://postgres/analysis_platform
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      KAFKA_ADDRESSES: kafka:19092
      EVENTEUM_ADDRESS: http://eventeum:8060/


  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      # - ./pg_data:/var/lib/postgresql/
      - /var/lib/postgresql/
      - ./init-db/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres_user
      # - POSTGRES_HOST_AUTH_METHOD=trust
      POSTGRES_PASSWORD: password
      POSTGRES_DB: eventeum

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "8124:9000"
    volumes:
      #- ./ch_data:/var/lib/clickhouse/
      - /var/lib/clickhouse/
      - ./init-db/clickhouse:/docker-entrypoint-initdb.d/
    environment:
      CLICKHOUSE_USER: clickhouse_user
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
      CLICKHOUSE_PASSWORD: password

  zookeeper:
    image: confluentinc/cp-zookeeper:5.0.1-1
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:5.0.1-1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
